###############################################################################
# Makefile for a script (e.g. Python) VMtranslator project
# Students:
# Alon Shevach, ID 205954209, alon.shevach@mail.huji.ac.il
# Dana Shulman, ID 315703371, Dana.Shulman@mail.huji.ac.il
###############################################################################

all:
	chmod a+x VMtranslator