###############################################################################
# Makefile for a script (e.g. Python) Assembler project 6
# Students:
# Alon Shevach, ID 205954209, alon.shevach@mail.huji.ac.il
# Dana Shulman, ID 315703371, dana.shulman@mail.huji.ac.il
###############################################################################


all:
	chmod a+x Assembler